sonar.projectKey=leonardoaragonez_tractor-store-backend
sonar.organization=leonardoaragonez
sonar.projectName=tractor-store-backend
sonar.sourceEncoding=UTF-8
sonar.java.source=21
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/package-info.java
